//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class tblQuestion
    {
        public int QuestionID { get; set; }
        public string Question { get; set; }
        public string OptionA { get; set; }
        public string OptionB { get; set; }
        public string OptionC { get; set; }
        public string OptionTrue { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public SelectList SubjectList { get; set; }
    }
}
